workflows:
  ios-workflow:
    name: iOS Build Workflow
    environment:
      groups:
        - app_credentials
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        flutter: "3.22.0"
    scripts:
      - name: Set up Flutter
        script: |
          flutter precache --ios
          flutter pub get
      
      - name: Fix iOS setup
        script: |
          flutter clean
          rm -rf ios/Podfile ios/Podfile.lock ios/Pods ios/Runner.xcworkspace
          flutter pub get
          cd ios
          pod repo update
          pod install --repo-update
          cd ..
      
      - name: Update iOS deployment target to 15.0
        script: |
          echo "Updating iOS deployment target to 15.0..."
          # Update Podfile
          sed -i '' 's/platform :ios, .*/platform :ios, '\''15.0'\''/' ios/Podfile
          
          # Update Xcode project settings
          /usr/libexec/PlistBuddy -c "Set :MinimumOSVersion 15.0" ios/Runner/Info.plist
          
          # Update project.pbxproj file
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = [^;]*;/IPHONEOS_DEPLOYMENT_TARGET = 15.0;/g' ios/Runner.xcodeproj/project.pbxproj
          
          echo "Deployment target updated to iOS 15.0"
      
      - name: Build iOS
        script: |
          flutter build ios --debug --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app
