ios-workflow:
  name: iOS Build Workflow
  instance_type: mac_mini_m2
  scripts:
    - name: Setup Flutter
      script: |
        flutter --version
        flutter pub get
        
    - name: Install iOS dependencies
      script: |
        cd ios
        pod install --repo-update
        cd ..
        
    - name: Build iOS
      script: |
        flutter build ios --debug --no-codesign
