workflows:
  ios-workflow:
    name: iOS Build Workflow
    environment:
      groups:
        - app_store_connect
      vars:
        BUNDLE_ID: "com.example.blockfoliox"
      # Use a Flutter version that includes Dart 3.9.0+
      flutter: "3.22.0"  # This version includes Dart 3.12.0
      xcode: latest
      cocoapods: default
    scripts:
      - name: Check Flutter version
        script: |
          flutter --version
          dart --version
      
      - name: Clean and regenerate iOS project
        script: |
          flutter clean
          rm -rf ios
          flutter create --platforms=ios .
      
      - name: Get dependencies
        script: |
          flutter pub get
      
      - name: Set up code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          keychain add-certificates
      
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
