workflows:
  ios-workflow:
    name: iOS Build Workflow
    environment:
      groups:
        - app_credentials
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        flutter: "3.22.0"
    instance_type: mac_mini_m2
    scripts:
      - name: Set up Flutter
        script: |
          flutter precache --ios
          flutter pub get
          flutter --version
      
      - name: Fix iOS setup
        script: |
          flutter clean
          rm -rf ios/Podfile ios/Podfile.lock ios/Pods ios/Runner.xcworkspace
          flutter pub get
      
      - name: Update iOS deployment target to 15.5
        script: |
          echo "Setting iOS deployment target to 15.5 for google_mlkit_commons..."
          
          # Update Podfile to iOS 15.5
          sed -i '' 's/platform :ios, .*/platform :ios, '\''15.5'\''/' ios/Podfile
          
          # Update Info.plist - ADD or UPDATE MinimumOSVersion
          if ! /usr/libexec/PlistBuddy -c "Print :MinimumOSVersion" ios/Runner/Info.plist 2>/dev/null; then
              echo "Adding MinimumOSVersion key to Info.plist..."
              /usr/libexec/PlistBuddy -c "Add :MinimumOSVersion string 15.5" ios/Runner/Info.plist
          else
              echo "Updating existing MinimumOSVersion key..."
              /usr/libexec/PlistBuddy -c "Set :MinimumOSVersion 15.5" ios/Runner/Info.plist
          fi
          
          # Update project.pbxproj deployment target
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = [^;]*;/IPHONEOS_DEPLOYMENT_TARGET = 15.5;/g' ios/Runner.xcodeproj/project.pbxproj
          
          echo "✅ Deployment target updated to iOS 15.5"
      
      - name: Install pods
        script: |
          cd ios
          pod repo update
          pod install --repo-update
          cd ..
      
      - name: Build iOS
        script: |
          flutter build ios --debug --no-codesign
      
      - name: Verify build settings
        script: |
          echo "Build completed! Verifying settings..."
          echo "Info.plist MinimumOSVersion:"
          /usr/libexec/PlistBuddy -c "Print :MinimumOSVersion" ios/Runner/Info.plist 2>/dev/null || echo "Key not found"
          echo "Podfile platform:"
          grep "platform :ios" ios/Podfile
          echo "✅ iOS 15.5 deployment target set - compatible with google_mlkit_commons"
    artifacts:
      - build/ios/iphoneos/*.app
