workflows:
  ios-workflow:
    name: iOS Build Workflow
    environment:
      groups:
        - app_credentials
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        flutter: "3.22.0"
    instance_type: mac_mini_m2
    scripts:
      - name: Set up Flutter
        script: |
          flutter precache --ios
          flutter pub get
          flutter --version
      
      - name: Fix iOS setup
        script: |
          flutter clean
          rm -rf ios/Podfile ios/Podfile.lock ios/Pods ios/Runner.xcworkspace
          flutter pub get
      
      - name: Update iOS deployment target to 15.0
        script: |
          echo "Setting iOS deployment target to 15.0 for maximum compatibility..."
          
          # Update Podfile to iOS 15.0
          sed -i '' 's/platform :ios, .*/platform :ios, '\''15.0'\''/' ios/Podfile
          
          # Update Info.plist MinimumOSVersion
          /usr/libexec/PlistBuddy -c "Set :MinimumOSVersion 15.0" ios/Runner/Info.plist
          
          # Update project.pbxproj deployment target
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = [^;]*;/IPHONEOS_DEPLOYMENT_TARGET = 15.0;/g' ios/Runner.xcodeproj/project.pbxproj
          
          echo "✅ Deployment target updated to iOS 15.0 - Supports iOS 15.0 to latest (18.0+)"
      
      - name: Install pods
        script: |
          cd ios
          pod repo update
          pod install --repo-update
          cd ..
      
      - name: Build iOS
        script: |
          flutter build ios --debug --no-codesign
      
      - name: Verify build settings
        script: |
          echo "Build completed! Verifying iOS 15.0 compatibility..."
          echo "Minimum OS Version:"
          plutil -p ios/Runner/Info.plist | grep MinimumOSVersion
          echo "Deployment Target:"
          grep "IPHONEOS_DEPLOYMENT_TARGET" ios/Runner.xcodeproj/project.pbxproj | head -1
          echo "✅ App will run on iOS 15.0, 16.0, 17.0, 18.0+"
    artifacts:
      - build/ios/iphoneos/*.app
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
