# Uncomment this line to define a global platform for your project
platform :ios, '15.0'

# CocoaPods analytics disabled
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

use_frameworks!
use_modular_headers!

target 'Runner' do
  flutter_application_path = '../'
  eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)
end
